author: TheIronMinerLv
website: www.side.lv
name: SideSurvivalPortals
description: Plugin for handling portal stuff in Side Survival server

main: lv.theironminerlv.sidesurvivalportals.SideSurvivalPortals
version: 1.0
api-version: 1.16
depend: [WorldGuard]

commands:
  test:
    description: test command
    usage: /<command>
    permission: sidesurvivalportals.test